homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  # 59.43587 17.00197 is Sionsberg according to https://latitude.to
  latitude: 59.43587
  longitude: 17.00197
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 26
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization file
  customize: !include customize.yaml
  # to be able to take snapshots
  whitelist_external_dirs:
  - '/tmp'
  
# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr
    name: Weather
#    forecast: 24
    monitored_conditions:
      - symbol
      - temperature
      - windSpeed
      - pressure
  - platform: haveibeenpwned
    email: 
      - tomas@primekey.se
      - tomas.gustavsson@primekey.com

#  - platform: random

camera:
  - platform: ffmpeg
    input: /dev/video0
  - platform: ffmpeg
    input: /dev/video1
  - platform: local_file
    name: Cam1 pic
    file_path: /tmp/snapshot_camera.ffmpeg.jpg
  - platform: local_file
    name: Cam2 pic
    file_path: /tmp/snapshot_camera.ffmpeg_2.jpg

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://hassio.local:3218

#action:
#  service: camera.snapshot
#  data:
#    entity_id: camera.yourcamera
#    filename: '/tmp/yourcamera_{{ now().strftime("%Y%m%d-%H%M%S") }}.jpg'

